// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mysql/check": {
            "post": {
                "description": "check sql through mskeeper",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Init API返回的UUID",
                        "name": "uuid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "执行的SQL",
                        "name": "sql",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "SQL执行的时间，单位：ms",
                        "name": "dura",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "SQL执行的参数，eg. [1,2,'333',4.44]",
                        "name": "args",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpsvr.RetData"
                        }
                    }
                }
            }
        },
        "/mysql/init": {
            "post": {
                "description": "通过dsn初始化mskeeper实例, dsn规则 https://www.cnblogs.com/diegodu/p/5586861.html",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "mskeeper session",
                        "name": "session",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "mysql dsn, eg. mskeeper_test:123456@tcp(192.168.0.86:3306)/mskeepertest?timeout=30s",
                        "name": "dsn",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpsvr.RetData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpsvr.RetData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/httpsvr.RetModel"
                },
                "msg": {
                    "type": "string"
                },
                "ret": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "httpsvr.RetModel": {
            "type": "object",
            "additionalProperties": true
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "2.0.1",
	Host:        "",
	BasePath:    "/v1/",
	Schemes:     []string{},
	Title:       "mskeeper",
	Description: "mskeeper api-server",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
