basePath: /v1/
definitions:
  httpsvr.RetData:
    properties:
      data:
        $ref: '#/definitions/httpsvr.RetModel'
        type: object
      msg:
        type: string
      ret:
        type: integer
      time:
        type: integer
    type: object
  httpsvr.RetModel:
    additionalProperties: true
    type: object
info:
  contact: {}
  description: mskeeper api-server
  license: {}
  title: mskeeper
  version: 2.0.1
paths:
  /mysql/check:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: check sql through mskeeper
      parameters:
      - description: Init API返回的UUID
        in: formData
        name: uuid
        required: true
        type: string
      - description: 执行的SQL
        in: formData
        name: sql
        required: true
        type: string
      - description: SQL执行的时间，单位：ms
        in: formData
        name: dura
        type: integer
      - description: SQL执行的参数，eg. [1,2,'333',4.44]
        in: formData
        name: args
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpsvr.RetData'
  /mysql/init:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过dsn初始化mskeeper实例, dsn规则 https://www.cnblogs.com/diegodu/p/5586861.html
      parameters:
      - description: mskeeper session
        in: formData
        name: session
        type: string
      - description: mysql dsn, eg. mskeeper_test:123456@tcp(192.168.0.86:3306)/mskeepertest?timeout=30s
        in: formData
        name: dsn
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpsvr.RetData'
swagger: "2.0"
